classdef (Abstract,Sealed) Viewer
methods (Static)
    commandInfo = Info()
    Help(command)
    AddPolygons(polygonsStruct)
    CaptureSpinMovie()
    ImageOut = CaptureWindow()
    Close()
    DeleteAllPolygons()
    Init(arrowFaces,arrowVerts,arrowNorms,sphereFaces,sphereVerts,shereNorms,pathStr)
    LoadTexture(Image,AnisotropicVoxelDimension,BufferType)
    MoveDown()
    MoveLeft()
    MoveRight()
    MoveUp()
    PeelUpdate(PeelSize)
    Play(playOn)
    MessageArray = Poll()
    ReleaseControl()
    RemovePolygon()
    ResetView()
    Rotate(on)
    PolygonLighting(lightOn)
    SetBackgroundColor(color)
    SetBorderColor(color)
    SetCapturePath(filePath,filePrefix)
    SetFrame(frame)
    SetRotation(deltaXangle,deltaYangle,deltaZangle)
    SetViewOrigin(viewOrigin)
    SetWindowSize(width,height)
    ShowAllPolygons(on)
    ShowFrameNumber(on)
    ShowLabels(on)
    ShowPolygonList(polygonIndices)
    ShowTexture(bufferType)
    ShowScaleBar(on)
    ShowWidget(on)
    TakeControl()
    TextureAttenuation(on)
    TextureLighting(lightOn)
    TransferFunction(TransferFunctionStruct,BufferType)
    ToggleWireframe(wireFrameOn)
    ZoomDecrement()
    ZoomIncrement()
end
methods (Static, Access = private)
    varargout = Mex(command, varargin)
end
end
