function [hull,track,family ] = GetEmptyStructs()
hull = struct(...
    'label',{},...
    'frame',{},...
    'centerOfMass',{},...
    'centerOfMassOrg',{},...
    'track',{},...
    'color',{},...
    'boundingBox',{},...
    'boundingBoxOrg',{},...
    'pixels',{},...
    'pixelsOrg',{},...
    'faces',{},...
    'verts',{},...
    'norms',{},...
    'distances',{}...
    );

track = struct(...
    'hulls',{},...
    'startFrame',{},...
    'endFrame',{},...
    'parentTrack',{},...
    'siblingTrack',{},...
    'childrenTracks',{},...
    'family',{},...
    'color',{});

family = struct(...
    'tracks',{},...
    'rootTrack',{},...
    'startFrame',{},...
    'endFrame',{});
end

