function UpdateTimeIndicatorLine(time)
global uiTreeFig uiTreeAx uiTimeLine uiControlHandles

if (isempty(uiTreeFig) || ~ishandle(uiTreeFig)|| isempty(uiTreeAx) ||~ishandle(uiTreeAx) || isempty(uiControlHandles) ||...
        ~ishandle(uiControlHandles.tb_curFrame)), return, end

if(ishandle(uiTimeLine))
    set(uiTimeLine,...
        'YData',        [time time],...
        'XData',        get(uiTreeAx,'XLim'));
else
    uiTimeLine = line(...
        get(uiTreeAx,'XLim'),...
        [time time],...
        'color',        'red',...
        'linewidth',    1,...
        'EraseMode',    'xor',...
        'Tag',          'timeIndicatorLine',...
        'Parent',       uiTreeAx);
end
